AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyCluster:
    Type: AWS::ECS::Cluster

  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-photo-bucket

  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: my-photo-queue

  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: my-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: nginx-nodejs
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80
          Essential: true
          Environment:
            - Name: S3_BUCKET
              Value: !Ref MyBucket
            - Name: SQS_QUEUE
              Value: !GetAtt MyQueue.QueueName
        - Name: ffmpeg-processor
          Image: ffmpeg:latest
          Essential: false
          Environment:
            - Name: S3_BUCKET
              Value: !Ref MyBucket
            - Name: SQS_QUEUE
              Value: !GetAtt MyQueue.QueueName

  MyService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyCluster
      TaskDefinition: !Ref MyTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-12345678
          SecurityGroups:
            - sg-12345678

  MyScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 10
      MinCapacity: 1
      ResourceId: !Join
        - /
        - - service
          - !Ref MyCluster
          - !GetAtt MyService.Name
      RoleARN: arn:aws:iam::123456789012:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  MyScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: MyScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref MyScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 5
        PredefinedMetricSpecification:
          PredefinedMetricType: SQSNumberOfMessagesVisible
          ResourceLabel: !GetAtt MyQueue.QueueName

Outputs:
  ClusterName:
    Description: The name of the ECS cluster
    Value: !Ref MyCluster
  BucketName:
    Description: The name of the S3 bucket
    Value: !Ref MyBucket
  QueueName:
    Description: The name of the SQS queue
    Value: !GetAtt MyQueue.QueueName
  ServiceName:
    Description: The name of the ECS service
    Value: !GetAtt MyService.Name